apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodz-app-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: foodz-app
  template:
    metadata:
      labels:
        app: foodz-app
    spec:
      containers:
        - name: foodz-app
          image: yash5090/foodz-app:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
